import React, { useMemo, useState } from 'react'
import Icon from '../components/Icon.jsx'
import ReflectionMap from '../components/ReflectionMap.jsx'
import { generateTreatment } from '../services/treatmentApi.js'

const regimeClass={'Synthèse stricte':'strict','Extraction stricte':'extract','Enrichissement contrôlé':'enrich'}
const groupOf=t=>['T01','T02','T04'].includes(t.traitement_id)?'Productions d’analyse':['T03','T05','T06','T08','T09'].includes(t.traitement_id)?'Productions de structuration et de veille':'Productions de diffusion et de détection'

export default function Atelier({data}){
 const [selected,setSelected]=useState(null),[need,setNeed]=useState('')
 const groups=useMemo(()=>Object.groupBy?Object.groupBy(data.treatments,groupOf):data.treatments.reduce((a,t)=>((a[groupOf(t)]??=[]).push(t),a),{}),[data])
 if(selected) return <Workspace treatment={selected} data={data} initialNeed={need} onBack={()=>setSelected(null)}/>
 return <main className="page workshop-page"><div className="workshop-grid"><section><div className="page-heading"><h1>Atelier de veille</h1><p>Je pars d’un besoin et je choisis une transformation.</p></div><div className="workshop-hero"><div className="compass-art">✦<div>✧</div></div><div><h2>Transformez vos besoins en productions à forte valeur</h2><p>L’atelier de veille vous aide à choisir la production la plus adaptée à votre besoin, en mobilisant les traitements d’IA les plus pertinents.</p><div className="need-box"><Icon name="spark"/><input value={need} onChange={e=>setNeed(e.target.value)} placeholder="Ex. : Comprendre les signaux faibles autour d’un phénomène…"/><button>Parcourir les productions <Icon name="chevron"/></button></div></div></div>{Object.entries(groups).map(([name,items])=><section className="treatment-group" key={name}><h2>{name}</h2><div className="treatment-grid">{items.map(t=><button className="treatment-card" key={t.traitement_id} onClick={()=>setSelected(t)}><div className="treat-icon"><Icon name={t.traitement_id==='T03'?'graph':t.traitement_id==='T09'?'pin':t.traitement_id==='T08'?'graph':t.traitement_id==='T10'?'warning':'spark'}/></div><div><small>Fonction : {t.fonction}</small><h3>{t.nom_traitement}</h3><p>{t.objectif}</p><span className={`regime ${regimeClass[t.regime_IA]||''}`}>{t.regime_IA}</span></div><Icon name="chevron"/></button>)}</div></section>)}</section><aside className="regime-panel"><h3>Les régimes IA disponibles <Icon name="info" size={16}/></h3><Regime cls="strict" title="Synthèse stricte">L’IA condense et organise l’information à partir de sources sélectionnées.</Regime><Regime cls="extract" title="Extraction stricte">L’IA extrait des éléments factuels sans interprétation.</Regime><Regime cls="enrich" title="Enrichissement contrôlé">Les propositions de l’IA sont clairement distinguées des informations issues des sources.</Regime></aside></div></main>
}

function Regime({cls,title,children}){return <div className={`regime-info ${cls}`}><div className="regime-icon">✦</div><div><strong>{title}</strong><p>{children}</p><span className={`regime ${cls}`}>{title}</span></div></div>}

function Workspace({treatment,data,onBack,initialNeed=''}){
 if(treatment.traitement_id==='T03') return <ReflectionWorkspace treatment={treatment} data={data} onBack={onBack} initialNeed={initialNeed}/>
 const pubs=data.publications.filter(p=>p.chunk_count>0).slice(0,20)
 const isT01=treatment.traitement_id==='T01'
 const [selected,setSelected]=useState(pubs.length?[pubs[0].publication_id]:[])
 const [need,setNeed]=useState(initialNeed)
 const [generation,setGeneration]=useState(null)
 const [loading,setLoading]=useState(false)
 const [error,setError]=useState('')
 const selectedPubs=pubs.filter(p=>selected.includes(p.publication_id))
 const togglePublication=id=>{setGeneration(null);setError('');if(isT01){setSelected([id]);return}setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 const runGeneration=async()=>{if(!isT01||!need.trim()||!selectedPubs.length||loading)return;setLoading(true);setError('');try{const result=await generateTreatment({treatment,need:need.trim(),publications:selectedPubs,contents:data.contents,nodes:data.nodes,relations:data.relations});setGeneration(result)}catch(e){setError(e?.message||String(e));setGeneration(null)}finally{setLoading(false)}}
 return <main className="page workspace-page"><button className="back-link" onClick={onBack}><Icon name="back"/>Retour à l’atelier</button><div className="workspace-head"><div><h1>{treatment.nom_traitement}</h1><p>{treatment.fonction}</p></div><span className={`regime ${regimeClass[treatment.regime_IA]||''}`}>{treatment.regime_IA}</span></div><div className="workspace-layout"><aside className="corpus-panel"><h3>Corpus sélectionné <span>{selected.length} source{selected.length>1?'s':''}</span></h3>{isT01&&<div className="corpus-scope-note"><Icon name="info" size={15}/><span>T01 est défini pour une publication : choisissez une source.</span></div>}{pubs.map(p=><label className={`corpus-item ${selected.includes(p.publication_id)?'selected':''}`} key={p.publication_id}><input type={isT01?'radio':'checkbox'} name={isT01?'t01-source':undefined} checked={selected.includes(p.publication_id)} onChange={()=>togglePublication(p.publication_id)}/>{p.has_image?<img src={`.${p.image_path}`} alt=""/>:<div className="mini-placeholder">{p.publication_id}</div>}<div><strong>{p.titre}</strong><span>{p.organisme_producteur} · {p.année_publication}</span></div></label>)}</aside><section className="production-panel"><div className="user-need"><label>Besoin utilisateur</label><textarea value={need} onChange={e=>{setNeed(e.target.value);setError('')}} placeholder="Décrivez le besoin, la question ou le livrable attendu…"/></div><div className="production-sheet"><h3>Cadre du traitement</h3><Row label="Objectif" value={treatment.objectif}/><Row label="Périmètre" value={treatment.perimetre}/><Row label="Documents compatibles" value={treatment.type_document_compatible}/><Row label="Données mobilisées" value={treatment.donnees_mobilisees}/><Row label="Format de sortie" value={treatment.format_sortie}/><Row label="Provenance exigée" value={treatment.provenance_exigee}/>{isT01?<GenerationT01 generation={generation} loading={loading} error={error} need={need} selectedCount={selectedPubs.length} onGenerate={runGeneration}/>:<div className="production-placeholder"><Icon name="spark" size={30}/><strong>Génération à connecter</strong><p>Le moteur commun sera branché progressivement.</p><button className="btn primary" disabled>Générer avec le corpus sélectionné</button></div>}</div></section><aside className="source-rules"><h3>Règles de production</h3><p><strong>Régime IA :</strong> {treatment.regime_IA}</p><p><strong>Interaction :</strong> {treatment.interaction_utilisateur}</p><p><strong>Mode :</strong> {treatment.mode_generation}</p><div className="source-rule"><Icon name="book"/><span>Les contenus produits doivent conserver leur provenance lorsque le traitement l’exige.</span></div>{isT01&&<div className="source-rule engine-rule"><Icon name="spark"/><span>Le moteur parcourt la matière documentaire nécessaire, puis vérifie chaque provenance avant d’afficher le résumé.</span></div>}</aside></div></main>
}

function ReflectionWorkspace({treatment,data,onBack,initialNeed=''}){
 const pubs=data.publications.filter(p=>p.chunk_count>0)
 const [selected,setSelected]=useState(pubs.length?[pubs[0].publication_id]:[])
 const [need,setNeed]=useState(initialNeed)
 const [generation,setGeneration]=useState(null)
 const [loading,setLoading]=useState(false)
 const [error,setError]=useState('')
 const selectedPubs=pubs.filter(p=>selected.includes(p.publication_id))
 const toggle=id=>{setError('');setGeneration(null);setSelected(s=>s.includes(id)?s.filter(x=>x!==id):(s.length>=4?s:[...s,id]))}
 const run=async()=>{if(!need.trim()||!selectedPubs.length||loading)return;setLoading(true);setError('');try{const result=await generateTreatment({treatment,need:need.trim(),publications:selectedPubs,contents:data.contents,nodes:data.nodes,relations:data.relations});setGeneration(result)}catch(e){setError(e?.message||String(e));setGeneration(null)}finally{setLoading(false)}}
 return <main className="page reflection-page"><button className="back-link" onClick={onBack}><Icon name="back"/>Retour à l’atelier</button><header className="reflection-head"><div><div className="reflection-title-row"><h1>Carte de réflexion assistée</h1><span className="regime enrich">Enrichissement contrôlé</span></div><p>Une première architecture pour structurer, stimuler et prolonger votre réflexion. La carte vous appartient : déplacez, modifiez, supprimez ou ajoutez des pistes.</p></div></header><div className="reflection-request"><Icon name="spark" size={20}/><textarea value={need} onChange={e=>{setNeed(e.target.value);setError('')}} placeholder="Ex. : Comment mieux anticiper les transformations de la délinquance des mineurs ?"/><button className="btn primary" onClick={run} disabled={!need.trim()||!selectedPubs.length||loading}>{loading?'Construction…':generation?'Recomposer la carte':'Construire la carte'}</button></div><div className="reflection-layout"><aside className="reflection-corpus"><div className="reflection-side-head"><div><strong>Corpus actif</strong><span>{selected.length} publication{selected.length>1?'s':''}</span></div><small>Jusqu’à 4 sources pour la V0</small></div><div className="reflection-corpus-list">{pubs.map(p=><label key={p.publication_id} className={`reflection-corpus-item ${selected.includes(p.publication_id)?'selected':''}`}><input type="checkbox" checked={selected.includes(p.publication_id)} onChange={()=>toggle(p.publication_id)}/>{p.has_image?<img src={`.${p.image_path}`} alt=""/>:<div className="mini-placeholder">{p.publication_id}</div>}<div><b>{p.publication_id}</b><strong>{p.titre}</strong><span>{p.organisme_producteur} · {p.année_publication}</span></div></label>)}</div><div className="reflection-control-note"><span>✦</span><p>Les nœuds <b>documentés</b> conservent leurs sources. Les <b>suggestions IA</b> et <b>questions</b> sont signalées comme telles.</p></div></aside><section className="reflection-main">{loading?<ReflectionLoading/>:error?<div className="reflection-state error"><span>⚠</span><strong>La carte n’a pas pu être générée</strong><p>{error}</p><button className="btn primary" onClick={run}>Réessayer</button></div>:generation?<><div className="reflection-map-meta"><div><span className="generated-kicker">CARTE ASSISTÉE · ENRICHISSEMENT CONTRÔLÉ</span><strong>{generation.map?.title||'Carte de réflexion'}</strong></div><span>{generation.selection?.chunks_mobilises||0} passages mobilisés</span></div><ReflectionMap result={generation}/></>:<ReflectionEmpty onGenerate={run} disabled={!need.trim()||!selectedPubs.length}/>}</section></div></main>
}

function ReflectionEmpty({onGenerate,disabled}){return <div className="reflection-empty"><div className="reflection-orbit"><span>?</span><i/><i/><i/></div><span className="generated-kicker">ESPACE DE TRAVAIL</span><h2>Donnez une forme à votre réflexion</h2><p>La carte fera émerger des dimensions documentées, des faisceaux explicatifs, des tensions et des pistes de prolongement, tout en séparant clairement le corpus des suggestions de l’IA.</p><div className="reflection-empty-branches"><span>Question / problème</span><span>Enjeux</span><span>Acteurs</span><span>Faisceaux explicatifs</span><span>Tensions</span><span>Prolongements</span></div><button className="btn primary" onClick={onGenerate} disabled={disabled}><Icon name="spark" size={17}/>Construire ma première carte</button></div>}
function ReflectionLoading(){return <div className="reflection-state loading"><div className="generation-spinner">✦</div><strong>La réflexion prend forme…</strong><p>Le moteur sélectionne les passages utiles, distingue ce qui est documenté de ce qui relève d’une piste IA, puis construit une carte volontairement respirante.</p><div className="thinking-steps"><span className="active">Structurer le besoin</span><span>Repérer les appuis documentaires</span><span>Ouvrir des prolongements</span></div></div>}

function GenerationT01({generation,loading,error,need,selectedCount,onGenerate}){if(loading)return <div className="generation-state loading"><div className="generation-spinner">✦</div><strong>Couverture documentaire et génération…</strong><p>Le moteur couvre la publication selon sa longueur et conserve les pages ou timecodes sources.</p></div>;if(error)return <div className="generation-state error"><span aria-hidden="true">⚠</span><strong>La génération n’a pas abouti</strong><p>{error}</p><button className="btn primary" onClick={onGenerate}>Réessayer</button></div>;if(!generation)return <div className="production-placeholder connected"><Icon name="spark" size={30}/><strong>Moteur T01 connecté</strong><p>Le résumé sera produit exclusivement à partir des chunks de la publication sélectionnée, avec pages ou timecodes contrôlés.</p><button className="btn primary" disabled={!need.trim()||!selectedCount} onClick={onGenerate}>Générer avec la source sélectionnée</button></div>;return <ResumeAnalytique result={generation} onRegenerate={onGenerate}/>}
function ResumeAnalytique({result,onRegenerate}){const out=result?.output||{};return <section className="generated-output"><header className="generated-output-head"><div><span className="generated-kicker">PRODUCTION IA · SYNTHÈSE STRICTE</span><h2>Résumé analytique</h2><p>{result?.corpus?.map(p=>p.titre).join(' · ')}</p></div><div className="generation-metrics"><span>{result?.selection?.chunks_retenus||0} chunks retenus</span><button onClick={onRegenerate}>↻ Régénérer</button></div></header><PointSection title="Sujet" point={out.sujet}/><PointSection title="Problématique" point={out.problematique}/><ListSection title="Résultats" items={out.resultats}/><ListSection title="Enseignements" items={out.enseignements}/>{out.nuances?.length>0&&<ListSection title="Nuances et précautions" items={out.nuances} subtle/>}<div className="generated-sources"><h3>Sources</h3>{(result?.corpus||[]).map(pub=><a key={pub.publication_id} href={pub.url||'#'} target="_blank" rel="noreferrer"><span aria-hidden="true">↗</span><span><strong>{pub.titre}</strong><small>{pub.organisme_producteur}{pub.annee_publication?` · ${pub.annee_publication}`:''}</small></span></a>)}</div></section>}
function PointSection({title,point}){if(!point?.texte)return null;return <section className="generated-section"><h3>{title}</h3><p>{point.texte}</p><ProvenanceChips provenances={point.provenances}/></section>}
function ListSection({title,items=[],subtle=false}){if(!items.length)return null;return <section className={`generated-section ${subtle?'subtle':''}`}><h3>{title}</h3><div className="generated-list">{items.map((item,i)=><article key={i}><span className="generated-index">{i+1}</span><div><p>{item.texte}</p><ProvenanceChips provenances={item.provenances}/></div></article>)}</div></section>}
function ProvenanceChips({provenances=[]}){if(!provenances.length)return null;const groups=new Map();provenances.forEach(p=>{const pub=p.publication_id||'Source';if(!groups.has(pub))groups.set(pub,{pages:[],timecodes:[],seen:new Set()});const g=groups.get(pub);const isTimecode=p.type==='timecode'||Boolean(p.timecode_debut)||Boolean(p.timecode_fin);const value=isTimecode?(p.label||[p.timecode_debut,p.timecode_fin].filter(Boolean).join('–')):String(p.page||p.label||'').trim();if(!value)return;const key=`${isTimecode?'t':'p'}|${value}`;if(g.seen.has(key))return;g.seen.add(key);(isTimecode?g.timecodes:g.pages).push(value)});const labels=[];groups.forEach((g,pub)=>{if(g.pages.length)labels.push(`${pub} · ${g.pages.map(p=>`p. ${p}`).join(' ; ')}`);if(g.timecodes.length)labels.push(`${pub} · ${g.timecodes.join(' ; ')}`)});if(!labels.length)return null;return <div className="provenance-chips">{labels.map((label,i)=><span key={`${label}-${i}`}>{label}</span>)}</div>}
function Row({label,value}){return <div className="sheet-row"><strong>{label}</strong><span>{value}</span></div>}
