import React, { useMemo, useState } from 'react'
import Icon from '../components/Icon.jsx'

const regimeClass={'Synthèse stricte':'strict','Extraction stricte':'extract','Enrichissement contrôlé':'enrich'}
const groupOf=t=>['T01','T02','T04'].includes(t.traitement_id)?'Productions d’analyse':['T03','T05','T06','T08','T09'].includes(t.traitement_id)?'Productions de structuration et de veille':'Productions de diffusion et de détection'

export default function Atelier({data}){
 const [selected,setSelected]=useState(null),[need,setNeed]=useState('')
 const groups=useMemo(()=>Object.groupBy?Object.groupBy(data.treatments,groupOf):data.treatments.reduce((a,t)=>((a[groupOf(t)]??=[]).push(t),a),{}),[data])
 if(selected) return <Workspace treatment={selected} data={data} onBack={()=>setSelected(null)}/>
 return <main className="page workshop-page"><div className="workshop-grid"><section><div className="page-heading"><h1>Atelier de veille</h1><p>Je pars d’un besoin et je choisis une transformation.</p></div><div className="workshop-hero"><div className="compass-art">✦<div>✧</div></div><div><h2>Transformez vos besoins en productions à forte valeur</h2><p>L’atelier de veille vous aide à choisir la production la plus adaptée à votre besoin, en mobilisant les traitements d’IA les plus pertinents.</p><div className="need-box"><Icon name="spark"/><input value={need} onChange={e=>setNeed(e.target.value)} placeholder="Ex. : Comprendre les signaux faibles autour d’un phénomène…"/><button>Parcourir les productions <Icon name="chevron"/></button></div></div></div>{Object.entries(groups).map(([name,items])=><section className="treatment-group" key={name}><h2>{name}</h2><div className="treatment-grid">{items.map(t=><button className="treatment-card" key={t.traitement_id} onClick={()=>setSelected(t)}><div className="treat-icon"><Icon name={t.traitement_id==='T09'?'pin':t.traitement_id==='T08'?'graph':t.traitement_id==='T10'?'warning':'spark'}/></div><div><small>Fonction : {t.fonction}</small><h3>{t.nom_traitement}</h3><p>{t.objectif}</p><span className={`regime ${regimeClass[t.regime_IA]||''}`}>{t.regime_IA}</span></div><Icon name="chevron"/></button>)}</div></section>)}</section><aside className="regime-panel"><h3>Les régimes IA disponibles <Icon name="info" size={16}/></h3><Regime cls="strict" title="Synthèse stricte">L’IA condense et organise l’information à partir de sources sélectionnées.</Regime><Regime cls="extract" title="Extraction stricte">L’IA extrait des éléments factuels sans interprétation.</Regime><Regime cls="enrich" title="Enrichissement contrôlé">Les propositions de l’IA sont clairement distinguées des informations issues des sources.</Regime></aside></div></main>
}
function Regime({cls,title,children}){return <div className={`regime-info ${cls}`}><div className="regime-icon">✦</div><div><strong>{title}</strong><p>{children}</p><span className={`regime ${cls}`}>{title}</span></div></div>}
function Workspace({treatment,data,onBack}){
 const pubs=data.publications.filter(p=>p.chunk_count>0).slice(0,20); const [selected,setSelected]=useState(pubs.slice(0,3).map(p=>p.publication_id)); const [need,setNeed]=useState('')
 return <main className="page workspace-page"><button className="back-link" onClick={onBack}><Icon name="back"/>Retour à l’atelier</button><div className="workspace-head"><div><h1>{treatment.nom_traitement}</h1><p>{treatment.fonction}</p></div><span className={`regime ${regimeClass[treatment.regime_IA]||''}`}>{treatment.regime_IA}</span></div><div className="workspace-layout"><aside className="corpus-panel"><h3>Corpus sélectionné <span>{selected.length} sources</span></h3>{pubs.map(p=><label className="corpus-item" key={p.publication_id}><input type="checkbox" checked={selected.includes(p.publication_id)} onChange={()=>setSelected(s=>s.includes(p.publication_id)?s.filter(x=>x!==p.publication_id):[...s,p.publication_id])}/>{p.has_image?<img src={`.${p.image_path}`} alt=""/>:<div className="mini-placeholder">{p.publication_id}</div>}<div><strong>{p.titre}</strong><span>{p.organisme_producteur} · {p.année_publication}</span></div></label>)}</aside><section className="production-panel"><div className="user-need"><label>Besoin utilisateur</label><textarea value={need} onChange={e=>setNeed(e.target.value)} placeholder="Décrivez le besoin, la question ou le livrable attendu…"/></div><div className="production-sheet"><h3>Cadre du traitement</h3><Row label="Objectif" value={treatment.objectif}/><Row label="Périmètre" value={treatment.perimetre}/><Row label="Documents compatibles" value={treatment.type_document_compatible}/><Row label="Données mobilisées" value={treatment.donnees_mobilisees}/><Row label="Format de sortie" value={treatment.format_sortie}/><Row label="Provenance exigée" value={treatment.provenance_exigee}/><div className="production-placeholder"><Icon name="spark" size={30}/><strong>Génération à connecter</strong><p>Le cadre, le corpus et la provenance sont prêts. Le branchement au service IA sera effectué dans l’étape d’intégration.</p><button className="btn primary" disabled={!need.trim()}>Générer avec le corpus sélectionné</button></div></div></section><aside className="source-rules"><h3>Règles de production</h3><p><strong>Régime IA :</strong> {treatment.regime_IA}</p><p><strong>Interaction :</strong> {treatment.interaction_utilisateur}</p><p><strong>Mode :</strong> {treatment.mode_generation}</p><div className="source-rule"><Icon name="book"/><span>Les contenus produits doivent conserver leur provenance lorsque le traitement l’exige.</span></div></aside></div></main>
}
function Row({label,value}){return <div className="sheet-row"><strong>{label}</strong><span>{value}</span></div>}
